package com.nzion.repository.notifier.utility;

/**
 * Created by User on 11/13/2015.
 */
public enum TemplateNames {
    APPOINTMENT_REQUEST_SCHEDULE_FOR_PATIENT,
    APPOINTMENT_REQUEST_SCHEDULE_FOR_DOCTOR,
    PREMIUM_APPOINTMENT_SUCCESS_PAYMENT_SMS_FOR_PATIENT,
    PREMIUM_APPOINTMENT_SUCCESS_PAYMENT_SMS_FOR_DOCTOR,
    TELECONSULTATION_VISIT_SUCCESS_PAYMENT_SMS_FOR_PATIENT,
    TELECONSULTATION_VISIT_SUCCESS_PAYMENT_SMS_FOR_DOCTOR,
    HOME_VISIT_APPOINTMENT_SUCCESS_PAYMENT_SMS_FOR_PATIENT,
    HOME_VISIT_APPOINTMENT_SUCCESS_PAYMENT_SMS_FOR_DOCTOR,

    HOME_VISIT_APPOINTMENT_RESCHEDULE_BY_CLINIC,
    TELECONSULTATION_VISIT_RESCHEDULE_BY_CLINIC,
    APPOINTMENT_REQUEST_RESCHEDULE_BY_CLINIC,
    APPOINTMENT_REQUEST_CONFIRMED_BY_CLINIC,
    APPOINTMENT_REQUEST_SUCCESS_PAYMENT_SMS_FOR_PATIENT,
    APPOINTMENT_REQUEST_SUCCESS_PAYMENT_SMS_FOR_DOCTOR,

    APPOINTMENT_REQUEST_RESCHEDULE_BY_PATIENT_SMS_TO_DOCTOR,
    HOME_VISIT_APPOINTMENT_RESCHEDULE_BY_PATIENT,
    TELECONSULTATION_VISIT_RESCHEDULE_BY_PATIENT,
    PREMIUM_APPOINTMENT_RESCHEDULE_BY_PATIENT,

    APPOINTMENT_REQUEST_CANCELLED_BY_PATIENT_SMS_TO_DOCTOR,
    APPOINTMENT_REQUEST_CANCELLED_BY_PATIENT_SMS_TO_PATIENT,

    PREMIUM_APPOINTMENT_CANCELLED_BY_CLINIC,
    HOME_VISIT_REQUEST_CANCELLATION_BY_CLINIC_APPOINTMENT_DET,
    HOME_VISIT_REQUEST_CANCELLATION_BY_CLINIC_REFUND_DET,
    TELECONSULTATION_VISIT_CANCELLATION_BY_CLINIC,

    REFERRAL_CONTRACT_ACCEPTED_SMS,
    REFERRAL_CONTRACT_ACCEPTED_MAIL,
    REFERRAL_CONTRACT_REJECTED_SMS,
    REFERRAL_CONTRACT_REJECTED_MAIL,
    REFERRAL_CONTRACT_VIEWED_SMS,
    REFERRAL_CONTRACT_ACCEPTED_SMS_RECEIPIENT,
    REFERRAL_CONTRACT_ACCEPTED_MAIL_RECEIPIENT,
    HOME_VISIT_REQUEST_CANCELLATION_BY_CLINIC_SMS_DOCTOR,
    PHARMACY_SUCCESSFUL_PAYMENT_SMS,
    REFERRAL_CONTRACT_SAVED_SMS,
    APPOINTMENT_CHECKEDOUT_SMS_PATIENT,
    WALKIN_PATIENT_APPOINTMENT_SMS_REFERRAL_DOC,
    SOAP_REFERRAL_ENCOUNTER_NOTE,
    SOAP_REFERRAL_ENCOUNTER_NOTE_PATIENT,
    RECOMMENDATION_ENCOUNTER_NOTE,

    NOTIFY_DOCTOR_TO_SET_CALENDAR,
    NOTIFY_DOCTOR_TO_CONFIRM_APPOINTMENT

}
