
CREATE TABLE service_type (
  SERVICE_CODE varchar(20) NOT NULL,
  DESCRIPTION varchar(255) default NULL,
  PRIMARY KEY  (`SERVICE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `service_main_group` (
  `SERVICE_CODE` varchar(20) NOT NULL,
  `SERVICE_MAIN_GROUP` varchar(255) default NULL,
  PRIMARY KEY  (`SERVICE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `service_sub_group` (
  `SERVICE_CODE` varchar(20) NOT NULL,
  `DESCRIPTION` varchar(255) default NULL,
  `SERVICE_MAIN_GROUP_CODE` varchar(20) default NULL,
  PRIMARY KEY  (`SERVICE_CODE`),
  KEY `SERVICE_MAIN_GROUP_CODE` (`SERVICE_MAIN_GROUP_CODE`),
  CONSTRAINT `service_sub_group_ibfk_1` FOREIGN KEY (`SERVICE_MAIN_GROUP_CODE`) REFERENCES `service_main_group` (`SERVICE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table `tariff_category` (
	`TARIFF_CODE` varchar (60),
	`TARIFF` varchar (765),
	`PATIENT_CATEGORY` varchar (765),
	`PRIMARY_PAYOR` varchar (765),
	`CORPORATE_ID` varchar (765)
)ENGINE=InnoDB DEFAULT CHARSET=utf8; 

insert into `tariff_category` (`TARIFF_CODE`, `TARIFF`, `PATIENT_CATEGORY`, `PRIMARY_PAYOR`, `CORPORATE_ID`) values('00','Normal','Cash',NULL,NULL);
insert into `tariff_category` (`TARIFF_CODE`, `TARIFF`, `PATIENT_CATEGORY`, `PRIMARY_PAYOR`, `CORPORATE_ID`) values('01','WARBA INSURANCE COMPANY','Insurance',NULL,NULL);
insert into `tariff_category` (`TARIFF_CODE`, `TARIFF`, `PATIENT_CATEGORY`, `PRIMARY_PAYOR`, `CORPORATE_ID`) values('02','Spurthy','Insurance',NULL,NULL);
insert into `tariff_category` (`TARIFF_CODE`, `TARIFF`, `PATIENT_CATEGORY`, `PRIMARY_PAYOR`, `CORPORATE_ID`) values('03','Staff','Cash',NULL,NULL);
insert into `tariff_category` (`TARIFF_CODE`, `TARIFF`, `PATIENT_CATEGORY`, `PRIMARY_PAYOR`, `CORPORATE_ID`) values('04','Apollo','Corporate','Corporate','01');
insert into `tariff_category` (`TARIFF_CODE`, `TARIFF`, `PATIENT_CATEGORY`, `PRIMARY_PAYOR`, `CORPORATE_ID`) values('05','Apollo','Corporate','Patient','02');

commit;

CREATE TABLE `patient_category` (
  `PATIENT_CODE` varchar(20) NOT NULL,
  `DESCRIPTION` varchar(255) default NULL,
  PRIMARY KEY  (`PATIENT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE clinic_tariff(
	SERVICE_TYPE VARCHAR(20) DEFAULT NULL,
	SERVICE_MAIN_GROUP VARCHAR(20) DEFAULT NULL,
	SERVICE_SUB_GROUP VARCHAR(20) DEFAULT NULL,
	PROCEDURE_CODE VARCHAR(255) DEFAULT NULL, 
	VISIT_TYPE BIGINT(20) DEFAULT NULL,
	DOCTOR BIGINT(20) DEFAULT NULL,
	TARIFF_CATEGORY VARCHAR(20) DEFAULT NULL,
	PATIENT_CATEGORY VARCHAR(20) DEFAULT NULL,
	CLINIC_SHARE DECIMAL(19,2) DEFAULT NULL,
    DOCTOR_SHARE DECIMAL(19,2) DEFAULT NULL,
    TECHNICIAN_SHARE DECIMAL(19,2) DEFAULT NULL,
    SERVICE_COST DECIMAL(19,2) DEFAULT NULL,
    MARKUP_PERCENT DECIMAL(19,2) DEFAULT NULL,
    MARKUP_AMOUNT DECIMAL(19,2) DEFAULT NULL,
    TAX_PERCENT DECIMAL(19,2) DEFAULT NULL,
    TAX_AMOUNT DECIMAL(19,2) DEFAULT NULL,
    BILLABLE_AMOUNT DECIMAL(19,2) DEFAULT NULL,
	FROM_DATE DATE DEFAULT NULL,
	
	
	
	FOREIGN KEY (SERVICE_TYPE) REFERENCES service_type(SERVICE_CODE),
	FOREIGN KEY (SERVICE_MAIN_GROUP) REFERENCES service_main_group(SERVICE_CODE),
	FOREIGN KEY (SERVICE_SUB_GROUP) REFERENCES service_sub_group(SERVICE_CODE),
	FOREIGN KEY (PROCEDURE_CODE) REFERENCES cpt(CPT_CODE),
	FOREIGN KEY (VISIT_TYPE) REFERENCES slot_type(ID),
	FOREIGN KEY (TARIFF_CATEGORY) REFERENCES tariff_category(TARIFF_CODE),
	
	FOREIGN KEY (PATIENT_CATEGORY) REFERENCES patient_category(PATIENT_CODE),
	FOREIGN KEY (DOCTOR) REFERENCES provider(ID)
	
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE clinic_tariff ADD THRU_DATE DATE;
ALTER TABLE clinic_tariff ADD COPAY DECIMAL(19,3) DEFAULT NULL AFTER BILLABLE_AMOUNT_MAX;
ALTER TABLE clinic_tariff ADD COPAY_TYPE VARCHAR(20) DEFAULT NULL AFTER COPAY;



