/*
SQLyog Community Edition- MySQL GUI v8.2 
MySQL - 5.0.51b-community-nt : Database - ecosmos


CREATE TABLE `bed_characteristic` (
  `ID` bigint(20) NOT NULL auto_increment,
  `IS_ACTIVE` bit(1) default NULL,
  `CREATED_BY` varchar(255) default NULL,
  `CREATE_TX_TIMESTAMP` datetime default NULL,
  `DEACTIVATION_REASON` varchar(255) default NULL,
  `UPDATE_BY` varchar(255) default NULL,
  `UPDATED_TX_TIMESTAMP` datetime default NULL,
  `VERSION` bigint(20) default NULL,
  `DESCRIPTION` varchar(255) default NULL,
  `NAME` varchar(255) default NULL,
  `DEACTIVATEDBY` bigint(20) default NULL,
  PRIMARY KEY  (`ID`),
  KEY `FK426AE5395A250A76` (`DEACTIVATEDBY`),
  CONSTRAINT `FK426AE5395A250A76` FOREIGN KEY (`DEACTIVATEDBY`) REFERENCES `person` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

/*Data for the table `bed_characteristic` */

insert  into `bed_characteristic`(`ID`,`IS_ACTIVE`,`CREATED_BY`,`CREATE_TX_TIMESTAMP`,`DEACTIVATION_REASON`,`UPDATE_BY`,`UPDATED_TX_TIMESTAMP`,`VERSION`,`DESCRIPTION`,`NAME`,`DEACTIVATEDBY`) values (1,NULL,NULL,NULL,NULL,NULL,NULL,1,'Air Suspension','Air Suspension',NULL);
insert  into `bed_characteristic`(`ID`,`IS_ACTIVE`,`CREATED_BY`,`CREATE_TX_TIMESTAMP`,`DEACTIVATION_REASON`,`UPDATE_BY`,`UPDATED_TX_TIMESTAMP`,`VERSION`,`DESCRIPTION`,`NAME`,`DEACTIVATEDBY`) values (2,NULL,NULL,NULL,NULL,NULL,NULL,1,'Bending Beds','Bending Beds',NULL);
insert  into `bed_characteristic`(`ID`,`IS_ACTIVE`,`CREATED_BY`,`CREATE_TX_TIMESTAMP`,`DEACTIVATION_REASON`,`UPDATE_BY`,`UPDATED_TX_TIMESTAMP`,`VERSION`,`DESCRIPTION`,`NAME`,`DEACTIVATEDBY`) values (3,NULL,NULL,NULL,NULL,NULL,NULL,1,'Dental Beds','Dental Beds',NULL);
insert  into `bed_characteristic`(`ID`,`IS_ACTIVE`,`CREATED_BY`,`CREATE_TX_TIMESTAMP`,`DEACTIVATION_REASON`,`UPDATE_BY`,`UPDATED_TX_TIMESTAMP`,`VERSION`,`DESCRIPTION`,`NAME`,`DEACTIVATEDBY`) values (4,NULL,NULL,NULL,NULL,NULL,NULL,1,'Slanting Bed','Slanting Bed',NULL);
insert  into `bed_characteristic`(`ID`,`IS_ACTIVE`,`CREATED_BY`,`CREATE_TX_TIMESTAMP`,`DEACTIVATION_REASON`,`UPDATE_BY`,`UPDATED_TX_TIMESTAMP`,`VERSION`,`DESCRIPTION`,`NAME`,`DEACTIVATEDBY`) values (5,NULL,NULL,NULL,NULL,NULL,NULL,1,'Baby Bed','Baby Bed',NULL);
insert  into `bed_characteristic`(`ID`,`IS_ACTIVE`,`CREATED_BY`,`CREATE_TX_TIMESTAMP`,`DEACTIVATION_REASON`,`UPDATE_BY`,`UPDATED_TX_TIMESTAMP`,`VERSION`,`DESCRIPTION`,`NAME`,`DEACTIVATEDBY`) values (6,NULL,NULL,NULL,NULL,NULL,NULL,1,'Attached Toilettories','Attached Toilettories',NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
