insert into `bedstatus` (`BEDSTATUS`, `COLOR`) values('BOOKED','#FFFFFF'),
('CLEANED','#FFFFFF'),
('CLEANINGINPROGRESS','#FFFFFF'),
 ('DISCHARGED','#FFFFFF'),
 ('OCCUPIED','#FFFFFF'),
('OUTOFSERVICE','#FFFFFF'),
('PENDINGCLEANING','#FFFFFF'),
('PENDINGDISCHARGE','#FFFFFF'),
('RESERVED','#FFFFFF');
