/*
SQLyog Community Edition- MySQL GUI v8.2 
MySQL - 5.0.51b-community-nt : Database - ecosmos
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `cleaning_methods` */

CREATE TABLE `cleaning_methods` (
  `ID` bigint(20) NOT NULL auto_increment,
  `IS_ACTIVE` bit(1) default NULL,
  `CREATED_BY` varchar(255) default NULL,
  `CREATE_TX_TIMESTAMP` datetime default NULL,
  `DEACTIVATION_REASON` varchar(255) default NULL,
  `UPDATE_BY` varchar(255) default NULL,
  `UPDATED_TX_TIMESTAMP` datetime default NULL,
  `VERSION` bigint(20) default NULL,
  `DESCRIPTION` varchar(255) default NULL,
  `METHOD_NAME` varchar(255) default NULL,
  `DEACTIVATEDBY` bigint(20) default NULL,
  `CLEANINGMETHODS` bigint(20) default NULL,
  PRIMARY KEY  (`ID`),
  KEY `FK715EB64CDBEB88C5` (`CLEANINGMETHODS`),
  KEY `FK715EB64C5A250A76` (`DEACTIVATEDBY`),
  CONSTRAINT `FK715EB64C5A250A76` FOREIGN KEY (`DEACTIVATEDBY`) REFERENCES `person` (`ID`),
  CONSTRAINT `FK715EB64CDBEB88C5` FOREIGN KEY (`CLEANINGMETHODS`) REFERENCES `bed_cleaning_request` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

/*Data for the table `cleaning_methods` */

insert  into `cleaning_methods`(`ID`,`IS_ACTIVE`,`CREATED_BY`,`CREATE_TX_TIMESTAMP`,`DEACTIVATION_REASON`,`UPDATE_BY`,`UPDATED_TX_TIMESTAMP`,`VERSION`,`DESCRIPTION`,`METHOD_NAME`,`DEACTIVATEDBY`,`CLEANINGMETHODS`) values (1,NULL,NULL,NULL,NULL,NULL,NULL,1,'Use Penyle','Use Penyle',NULL,NULL);
insert  into `cleaning_methods`(`ID`,`IS_ACTIVE`,`CREATED_BY`,`CREATE_TX_TIMESTAMP`,`DEACTIVATION_REASON`,`UPDATE_BY`,`UPDATED_TX_TIMESTAMP`,`VERSION`,`DESCRIPTION`,`METHOD_NAME`,`DEACTIVATEDBY`,`CLEANINGMETHODS`) values (2,NULL,NULL,NULL,NULL,NULL,NULL,1,'Use Penyle','Use Acid',NULL,NULL);
insert  into `cleaning_methods`(`ID`,`IS_ACTIVE`,`CREATED_BY`,`CREATE_TX_TIMESTAMP`,`DEACTIVATION_REASON`,`UPDATE_BY`,`UPDATED_TX_TIMESTAMP`,`VERSION`,`DESCRIPTION`,`METHOD_NAME`,`DEACTIVATEDBY`,`CLEANINGMETHODS`) values (3,NULL,NULL,NULL,NULL,NULL,NULL,1,'Use Penyle','Use Disinfectant For Blankets',NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
