INSERT INTO `drug_dosage_route`(`ID`,`IS_ACTIVE`,`CREATED_BY`,`CREATE_TX_TIMESTAMP`,`DEACTIVATION_REASON`,`UPDATE_BY`,`UPDATED_TX_TIMESTAMP`,`VERSION`,`CODE`,`DESCRIPTION`,`DEACTIVATEDBY`) VALUES (1,1,null,null,null,'cricket','2011-02-24 20:13:05',1,'Oral','Oral',null)
, (2,null,null,null,null,null,null,0,'Intravenous','Intravenous',null)
, (3,null,null,null,null,null,null,0,'Subcutaneous','Subcutaneous',null)
, (4,null,null,null,null,null,null,0,'Intraperitoneal','Intraperitoneal',null)
, (5,null,null,null,null,null,null,0,'Intramuscular','Intramuscular',null)
, (6,null,null,null,null,null,null,0,'Intrathoracic','Intrathoracic',null)
, (7,null,null,null,null,null,null,0,'Intra-Articular','Intra-Articular',null)
, (8,null,null,null,null,null,null,0,'Intradermal','Intradermal',null)
, (9,null,null,null,null,null,null,0,'Epidural','Epidural',null)
, (11,1,null,null,null,'cricket','2011-02-25 00:30:14',1,'Topical','Topical',null)
, (12,null,null,null,null,null,null,0,'Ophthalmic','Ophthalmic',null)
, (13,null,null,null,null,null,null,0,'Auricular (Otic)','Auricular (Otic)',null)
, (14,null,null,null,null,null,null,0,'Nasal','Nasal',null)
, (15,null,null,null,null,null,null,0,'Vaginal','Vaginal',null)
, (16,1,null,null,null,'cricket','2011-02-25 11:13:43',1,'Rectal','Rectal',null)
, (17,null,null,null,null,null,null,0,'Urethral','Urethral',null)
, (19,null,null,null,null,null,null,0,'Intrasynovial','Intrasynovial',null)
, (20,null,null,null,null,null,null,0,'Intratumor','Intratumor',null)
, (21,null,null,null,null,null,null,0,'Intravascular','Intravascular',null)
, (22,null,null,null,null,null,null,0,'Intraspinal','Intraspinal',null)
, (23,null,null,null,null,null,null,0,'Intracavitary','Intracavitary',null)
, (24,null,null,null,null,null,null,0,'Sublingual','Sublingual',null)
, (27,null,null,null,null,null,null,0,'Intracardiac','Intracardiac',null)
, (28,null,null,null,null,null,null,0,'Intrauterine','Intrauterine',null)
, (30,null,null,null,null,null,null,0,'Buccal','Buccal',null)
, (32,null,null,null,null,null,null,0,'Irrigation','Irrigation',null)
, (34,null,null,null,null,null,null,0,'Retrobulbar','Retrobulbar',null)
, (35,null,null,null,null,null,null,0,'Intratracheal','Intratracheal',null)
, (36,null,null,null,null,null,null,0,'Intraocular','Intraocular',null)
, (37,null,null,null,null,null,null,0,'Intra-Arterial','Intra-Arterial',null)
, (38,null,null,null,null,null,null,0,'Dental','Dental',null)
, (40,null,null,null,null,null,null,0,'Periodontal','Periodontal',null)
, (42,null,null,null,null,null,null,0,'Intralesional','Intralesional',null)
, (43,null,null,null,null,null,null,0,'Intrapleural','Intrapleural',null)
, (46,null,null,null,null,null,null,0,'Intragastric','Intragastric',null)
, (53,null,null,null,null,null,null,0,'Submucosal','Submucosal',null)
, (55,null,null,null,null,null,null,0,'Iontophoresis','Iontophoresis',null)
, (57,null,null,null,null,null,null,0,'Extracorporeal','Extracorporeal',null)
, (61,null,null,null,null,null,null,0,'Intraprostatic','Intraprostatic',null)
, (66,null,null,null,null,null,null,0,'Subarachnoid','Subarachnoid',null)
, (68,null,null,null,null,null,null,0,'Conjunctival','Conjunctival',null)
, (71,null,null,null,null,null,null,0,'Nasogastric','Nasogastric',null)
, (96,null,null,null,null,null,null,0,'Subconjunctival','Subconjunctival',null)
, (103,null,null,null,null,null,null,0,'Intrathecal','Intrathecal',null)
, (109,null,null,null,null,null,null,0,'Soft Tissue','Soft Tissue',null)
, (110,null,null,null,null,null,null,0,'Intratesticular','Intratesticular',null)
, (113,1,null,null,null,'test','2011-02-23 11:02:45',1,'Percutaneous','Percutaneous',null)
, (119,null,null,null,null,null,null,0,'Intracoronary','Intracoronary',null)
, (122,null,null,null,null,null,null,0,'Transmucosal','Transmucosal',null)
, (128,null,null,null,null,null,null,0,'Intravesical','Intravesical',null)
, (132,null,null,null,null,null,null,0,'Intracavernous','Intracavernous',null)
, (135,null,null,null,null,null,null,0,'Other','Other',null)
, (136,null,null,null,null,null,null,0,'Respiratory (Inhalation)','Respiratory (Inhalation)',null)
, (311,null,null,null,null,null,null,0,'Intravitreal','Intravitreal',null)
, (312,null,null,null,null,null,null,0,'Not Applicable','Not Applicable',null)
, (358,null,null,null,null,null,null,0,'Transdermal','Transdermal',null)
, (361,null,null,null,null,null,null,0,'Infiltration','Infiltration',null)
, (364,null,null,null,null,null,null,0,'Laryngeal','Laryngeal',null)
, (400,null,null,null,null,null,null,0,'Unassigned','Unassigned',null)
, (410,null,null,null,null,null,null,0,'Oropharyngeal','Oropharyngeal',null)
, (411,null,null,null,null,null,null,0,'Parenteral','Parenteral',null)
, (413,null,null,null,null,null,null,0,'Intracaudal','Intracaudal',null);

