INSERT INTO `drug_dosage_form_master`(`ID`,`IS_ACTIVE`,`CREATED_BY`,`CREATE_TX_TIMESTAMP`,`DEACTIVATION_REASON`,`UPDATE_BY`,`UPDATED_TX_TIMESTAMP`,`VERSION`,`CODE`,`DESCRIPTION`,`DEACTIVATEDBY`,`PRACTICE_ID`) VALUES (52,null,null,null,null,null,null,0,'Emulsion','Emulsion',null,null)
, (64,null,null,null,null,null,null,0,'Gas','Gas',null,null)
, (66,null,null,null,null,null,null,0,'Gel','Gel',null,null)
, (78,null,null,null,null,null,null,0,'Gran','Granule',null,null)
, (80,null,null,null,null,null,null,0,'Gran Effrv','Granule, Effervescent',null,null)
, (85,null,null,null,null,null,null,0,'Gum','Gum, Chewing',null,null)
, (98,null,null,null,null,null,null,0,'Oil','Oil',null,null)
, (101,1,null,null,null,'cricket','2011-02-25 00:30:14',1,'Ointment','Ointment',null,null)
, (103,null,null,null,null,null,null,0,'Paste','Paste',null,null)
, (105,null,null,null,null,null,null,0,'Pellet','Pellet',null,null)
, (110,null,null,null,null,null,null,0,'Pwd','Powder',null,null)
, (138,1,null,null,null,'test','2011-02-23 11:02:45',1,'Sol','Solution',null,null)
, (173,1,null,null,null,'cricket','2011-02-25 11:13:43',1,'Supp','Suppository',null,null)
, (177,null,null,null,null,null,null,0,'Susp','Suspension',null,null)
, (246,null,null,null,null,null,null,0,'Aer','Aerosol',null,null)
, (256,null,null,null,null,null,null,0,'Disc','Disc',null,null)
, (260,null,null,null,null,null,null,0,'IUD','Intrauterine Device',null,null)
, (271,null,null,null,null,null,null,0,'Sponge','Sponge',null,null)
, (272,null,null,null,null,null,null,0,'Spray','Spray',null,null)
, (276,null,null,null,null,null,null,0,'Swab','Swab',null,null)
, (278,null,null,null,null,null,null,0,'Tape','Tape',null,null)
, (285,null,null,null,null,null,null,0,'Dressing','Dressing',null,null)
, (286,null,null,null,null,null,null,0,'Enema','Enema',null,null)
, (293,null,null,null,null,null,null,0,'Inhalant','Inhalant',null,null)
, (299,null,null,null,null,null,null,0,'Liq','Liquid',null,null)
, (300,null,null,null,null,null,null,0,'Lotion','Lotion',null,null)
, (304,null,null,null,null,null,null,0,'Shampoo','Shampoo',null,null)
, (305,null,null,null,null,null,null,0,'Soap','Soap',null,null)
, (307,null,null,null,null,null,null,0,'Syrup','Syrup',null,null)
, (313,null,null,null,null,null,null,0,'Not Applicable','Not Applicable',null,null)
, (339,null,null,null,null,null,null,0,'Aer Met','Aerosol, Metered',null,null)
, (345,null,null,null,null,null,null,0,'Spray Met','Spray, Metered',null,null)
, (347,null,null,null,null,null,null,0,'Bar Chew','Bar, Chewable',null,null)
, (363,null,null,null,null,null,null,0,'Troche','Troche',null,null)
, (500,1,null,null,null,'test','2011-02-23 11:02:45',1,'Tab','Tablet',null,null)
, (501,null,null,null,null,null,null,0,'Tab Chew','Tablet, Chewable',null,null)
, (503,null,null,null,null,null,null,0,'Tab Effrv','Tablet, Effervescent',null,null)
, (510,null,null,null,null,null,null,0,'Tab ER','Tablet, Extended Release',null,null)
, (520,null,null,null,null,null,null,0,'Tab DR','Tablet, Delayed Release',null,null)
, (522,null,null,null,null,null,null,0,'Tab Orally','Tablet, Orally Disintegrating',null,null)
, (600,null,null,null,null,null,null,0,'Cap','Capsule',null,null)
, (603,null,null,null,null,null,null,0,'Cap Coated Pellets','Capsule, Coated Pellets',null,null)
, (610,null,null,null,null,null,null,0,'Cap ER','Capsule, Extended Release',null,null)
, (621,null,null,null,null,null,null,0,'Cap DR Pel','Capsule, Delayed Release Pellets',null,null)
, (700,null,null,null,null,null,null,0,'Inj','Injection',null,null)
, (715,null,null,null,null,null,null,0,'Imp','Implant',null,null)
, (717,null,null,null,null,null,null,0,'Sol GF ER','Solution, Gel Forming, Extended Release',null,null)
, (805,null,null,null,null,null,null,0,'Cream','Cream',null,null)
, (807,null,null,null,null,null,null,0,'Elixir','Elixir',null,null)
, (809,null,null,null,null,null,null,0,'Gran F/Recon','Granule, for Reconstitution',null,null)
, (810,1,null,null,null,'test','2011-02-23 11:02:45',1,'Film ER','Film, Extended Release',null,null)
, (812,null,null,null,null,null,null,0,'Insert ER','Insert, Extended Release',null,null)
, (816,null,null,null,null,null,null,0,'Susp ER','Suspension, Extended Release',null,null)
, (831,null,null,null,null,null,null,0,'Lozenge','Lozenge',null,null)
, (837,null,null,null,null,null,null,0,'Tincture','Tincture',null,null)
, (841,null,null,null,null,null,null,0,'Pwd Met','Powder, Metered',null,null)
, (900,null,null,null,null,null,null,0,'Unassigned','Unassigned',null,null)
, (930,null,null,null,null,null,null,0,'Fiber ER','Fiber, Extended Release',null,null)
, (932,null,null,null,null,null,null,0,'Inj Lipid','Injectable, Lipid Complex',null,null)
, (933,null,null,null,null,null,null,0,'Inj Liposomal','Injectable, Liposomal',null,null)
, (934,null,null,null,null,null,null,0,'Insert','Insert',null,null)
, (935,null,null,null,null,null,null,0,'Jelly','Jelly',null,null)
, (936,null,null,null,null,null,null,0,'Liq ER','Liquid Extended Release',null,null)
, (941,null,null,null,null,null,null,0,'Pwd F/Recon','Powder for Reconstitution',null,null)
, (942,null,null,null,null,null,null,0,'Drops','Drops',null,null)
, (944,null,null,null,null,null,null,0,'Tab Disp','Tablet, Dispersible',null,null)
, (945,null,null,null,null,null,null,0,'Lip Balm','Lip Balm',null,null)
, (946,null,null,null,null,null,null,0,'Foam','Foam',null,null)
, (947,null,null,null,null,null,null,0,'Sol GF','Solution, Gel Forming',null,null)
, (948,null,null,null,null,null,null,0,'Film','Film',null,null)
, (949,null,null,null,null,null,null,0,'Oral Strip','Oral Dissolving Strip',null,null)
, (950,null,null,null,null,null,null,0,'Tab Mod Rel','Tablet, Modified-Release',null,null)
, (951,null,null,null,null,null,null,0,'Cap Mod Rel','Capsule, Modified Release',null,null)
, (952,null,null,null,null,null,null,0,'Susp Mod Rel','Suspension, Modified Release',null,null)
, (955,null,null,null,null,null,null,0,'Tab SL','Tablet, Sublingual',null,null)
, (956,null,null,null,null,null,null,0,'Ophth Strip','Ophthalmic Strip',null,null)
, (957,null,null,null,null,null,null,0,'Tablet for Oral Susp','Tablet for Oral Suspension',null,null)
, (958,null,null,null,null,null,null,0,'Cap/Tab','Capsule/Tablet',null,null)
, (959,null,null,null,null,null,null,0,'Patch','Patch',null,null);

