INSERT  INTO `password_policy`(`CREATED_BY`,`CREATE_TX_TIMESTAMP`,`VERSION`,`PWD_MAX_REPEATED_CHARS`,`PWD_EXPIRE_WARNING`,`PWD_GRACE_LOGIN_LIMIT`,`PWD_CHECK_SYNTAX`,`PWD_FAILURE_COUNT_INTERVAL`,`PWD_IN_HISTORY`,`PWD_MAX_AGE`,`PWD_MAX_FAILURE`,`PWD_MIN_LENGTH`,`PWD_MUST_CHANGE`,`SELECTED_PATTERN`,`SESSION_TIME_OUT`) VALUES ('SEED',NOW(),2,NULL,NULL,NULL,TRUE,NULL,NULL,100,3,8,'','([0-9]+(\\p{Alpha})+)+([0-9]*(\\p{Alpha})*)*|((\\p{Alpha})+[0-9]+)([0-9]*(\\p{Alpha})*)*',600);

INSERT INTO USER_LOGIN (IMPERSONATED,VERSION,USERNAME,PASSWORD,IS_ACTIVE, ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED,CREDENTIALS_NON_EXPIRED,SUCCESSIVE_FAILED_LOGINS,IS_REQUIRE_PASSWORD_CHANGE,ROLES,ACCEPTED_TERMS_AND_CONDITIONS) VALUES (FALSE,0,'superadmin', 'superadmin', TRUE, TRUE, TRUE, TRUE, 0, FALSE,576460752303423488,true);

DELETE FROM SLOT_TYPE;

DELETE FROM ENTITY_SEQUENCES;


INSERT INTO PKGENERATOR(CLASSNAME,PK_VALUE) values ('com.nzion.domain.emr.SoapModule',0);


source enumeration_seed.sql

-- source cpt.sql
-- source icd_element.sql
-- source loinc.sql
-- source lab_specimen_source.sql
-- source \.sql

-- source drug_sig.sql
-- source granted_security_permission.sql
-- commit;
source unit_of_measurement.sql;
commit;
-- source lab_specimen_source.sql;
commit;
-- source bed_characters.sql
commit;
-- source bed_status.sql
commit;
-- source productCategory.sql
commit;
-- source discharge_section_metadata.sql;
commit;
source speciality.sql;
commit;
source chiefcomplaints.sql;
commit;
source speciality-chiefcomplaint.sql;
commit;
source preference.sql;
commit;
source age_group_seed.sql;
commit;

INSERT INTO REFERRAL(ID,IS_ACTIVE,CREATED_BY,CREATE_TX_TIMESTAMP,UPDATE_BY,UPDATED_TX_TIMESTAMP,VERSION,FIRST_NAME,LAST_NAME)
VALUES (9000,TRUE,'admin',SYSDATE(),'admin',SYSDATE(),1,'SELF','');

INSERT INTO PERSON (ID,IS_ACTIVE,CREATED_BY,CREATE_TX_TIMESTAMP,UPDATE_BY,UPDATED_TX_TIMESTAMP,VERSION,ACCOUNT_NUMBER,
PARTY_TYPE,CORPORATE_EMAIL,EMAIL,MOBILE_NUMBER,OFFICE_PHONE,ADDRESS1,CITY,POSTAL_CODE,STATE_PROVINCE_GEO,
FIRST_NAME,LAST_NAME,SCHEDULABLE)
VALUES(9000,TRUE,'admin',SYSDATE(),'admin',SYSDATE(),1,9000,'PROVIDER','','','','','','','','',
'INHOUSE DOCTOR','',TRUE);

INSERT INTO EMPLOYEE (ID) VALUES(9000);

INSERT INTO PROVIDER (ID,PROVIDER_ASSISTANT) VALUES (9000,FALSE);

ALTER TABLE invoice MODIFY `COLLECTED_PRICE` DECIMAL (19,3), MODIFY `AMOUNT` DECIMAL (19,3),MODIFY `WRITTENOFF_PRICE` DECIMAL (19,3),
MODIFY `TOTAL_AUTHORIZATION_AMOUNT` DECIMAL (19,3),MODIFY `TOTAL_COPAY_AMOUNT` DECIMAL (19,3),MODIFY `TOTAL_DEDUCTABLE_AMOUNT` DECIMAL (19,3);


ALTER TABLE `clinic_tariff` MODIFY `CLINIC_SHARE` DECIMAL (19,3), MODIFY `DOCTOR_SHARE` DECIMAL (19,3), MODIFY `TECHNICIAN_SHARE` DECIMAL (19,3),
MODIFY `SERVICE_COST` DECIMAL (19,3), MODIFY `MARKUP_PERCENT` DECIMAL (19,3), MODIFY `MARKUP_AMOUNT` DECIMAL (19,3), MODIFY `TAX_PERCENT` DECIMAL (19,3),
MODIFY `TAX_AMOUNT` DECIMAL (19,3), MODIFY `BILLABLE_AMOUNT` DECIMAL (19,3);

ALTER TABLE clinic_tariff ADD BILLABLE_AMOUNT_MIN DECIMAL(19,3) AFTER TAX_AMOUNT;
ALTER TABLE clinic_tariff ADD BILLABLE_AMOUNT_MAX DECIMAL(19,3) AFTER BILLABLE_AMOUNT;
ALTER TABLE clinic_tariff ADD TELE_CONSULTATION_ALLOWED BIT(1) DEFAULT NULL AFTER BILLABLE_AMOUNT_MAX;


ALTER TABLE `invoice_item` MODIFY `CESS_AMOUNT` DECIMAL (19,3), MODIFY `FACTOR`  DECIMAL (19,3), MODIFY `AMOUNT` DECIMAL (19,3),MODIFY `TAX_AMOUNT` DECIMAL (19,3),
 MODIFY `AUTHORIZATION` DECIMAL (19,3), MODIFY `AUTHORIZATION_AMOUNT` DECIMAL (19,3),MODIFY `AUTHORIZATION_INCLUSIVE_CONSULTATION` DECIMAL (19,3), 
 MODIFY `AUTHORIZATION_REQUIRED_CONSULTATION` DECIMAL (19,3),MODIFY `COPAY_AMOUNT` DECIMAL (19,3),MODIFY `DEDUCTABLE_AMOUNT` DECIMAL (19,3),
MODIFY `CONCESSION_AMOUNT` DECIMAL (19,3),MODIFY `NET_PRICE` DECIMAL (19,3) ,MODIFY `COPAY_PERCENTAGE` DECIMAL (19,3), MODIFY `DEDUCTABLE_PERCENTAGE`  DECIMAL (19,3);


ALTER TABLE `invoice_payment` MODIFY `AMOUNT` DECIMAL (19,3);

ALTER TABLE `acctg_transaction_entry` MODIFY `AMOUNT` DECIMAL (19,3);

INSERT INTO `dm_category` (`ID`, `IS_ACTIVE`, `CREATED_BY`, `CREATE_TX_TIMESTAMP`, `DEACTIVATION_REASON`, `UPDATE_BY`, `UPDATED_TX_TIMESTAMP`, `VERSION`, `DESCRIPTION`, `NAME`, `DEACTIVATEDBY`, `PARENT_ID`) VALUES('10000','','admin','2015-03-03 16:09:22',NULL,NULL,NULL,'1',NULL,'Patient ID',NULL,NULL);


