INSERT INTO `organ_systems`(`IS_ACTIVE`,`VERSION`,`ORGAN_SYSTEM_DESC`) VALUES (1,0,'Constitutional symptoms');
INSERT INTO `organ_systems`(`IS_ACTIVE`,`VERSION`,`ORGAN_SYSTEM_DESC`) VALUES (1,0,'Eyes');
INSERT INTO `organ_systems`(`IS_ACTIVE`,`VERSION`,`ORGAN_SYSTEM_DESC`) VALUES (1,0,'Ears, Nose, Mouth, Throat');
INSERT INTO `organ_systems`(`IS_ACTIVE`,`VERSION`,`ORGAN_SYSTEM_DESC`) VALUES (1,0,'Cardiovascular');
INSERT INTO `organ_systems`(`IS_ACTIVE`,`VERSION`,`ORGAN_SYSTEM_DESC`) VALUES (1,0,'Respiratory');
INSERT INTO `organ_systems`(`IS_ACTIVE`,`VERSION`,`ORGAN_SYSTEM_DESC`) VALUES (1,0,'Gastrointestinal');
INSERT INTO `organ_systems`(`IS_ACTIVE`,`VERSION`,`ORGAN_SYSTEM_DESC`) VALUES (1,0,'Genitourinary');
INSERT INTO `organ_systems`(`IS_ACTIVE`,`VERSION`,`ORGAN_SYSTEM_DESC`) VALUES (1,0,'Musculoskeletal');
INSERT INTO `organ_systems`(`IS_ACTIVE`,`VERSION`,`ORGAN_SYSTEM_DESC`) VALUES (1,0,'Integumentary (skin and/or breast)');
INSERT INTO `organ_systems`(`IS_ACTIVE`,`VERSION`,`ORGAN_SYSTEM_DESC`) VALUES (1,0,'Neurological');
INSERT INTO `organ_systems`(`IS_ACTIVE`,`VERSION`,`ORGAN_SYSTEM_DESC`) VALUES (1,0,'Psychiatric');
INSERT INTO `organ_systems`(`IS_ACTIVE`,`VERSION`,`ORGAN_SYSTEM_DESC`) VALUES (1,0,'Endocrine');
INSERT INTO `organ_systems`(`IS_ACTIVE`,`VERSION`,`ORGAN_SYSTEM_DESC`) VALUES (1,0,'Hematologic/Lymphatic');
INSERT INTO `organ_systems`(`IS_ACTIVE`,`VERSION`,`ORGAN_SYSTEM_DESC`) VALUES (1,0,'Allergic/Immunologic');