
INSERT INTO `slot_type`(`VERSION`,`IS_ACTIVE`,`CHILD_TYPE`,`DESCRIPTION`,`NAME`,`CHARGE_TYPE`) VALUES (0,1,'SOAP_NOTE_TYPE','Consult Visit','Consult Visit','INPATIENT');
INSERT INTO `slot_type`(`VERSION`,`IS_ACTIVE`,`CHILD_TYPE`,`DESCRIPTION`,`NAME`,`CHARGE_TYPE`) VALUES (0,1,'SOAP_NOTE_TYPE','Followup Visit','Followup Visit','INPATIENT');
INSERT INTO `slot_type`(`VERSION`,`IS_ACTIVE`,`CHILD_TYPE`,`DESCRIPTION`,`NAME`,`CHARGE_TYPE`) VALUES (0,1,'SOAP_NOTE_TYPE','Problem Visit ','Problem Visit','INPATIENT');
INSERT INTO `slot_type`(`VERSION`,`IS_ACTIVE`,`CHILD_TYPE`,`DESCRIPTION`,`NAME`,`CHARGE_TYPE`) VALUES (0,1,'SOAP_NOTE_TYPE','Routine CheckUp','Routine CheckUp,'INPATIENT'');
INSERT INTO `slot_type`(`VERSION`,`IS_ACTIVE`,`CHILD_TYPE`,`DESCRIPTION`,`NAME`,`CHARGE_TYPE`) VALUES (0,1,'SOAP_NOTE_TYPE','Inpatient CheckUp','Inpatient CheckUp','INPATIENT');

